// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("WebApplication1.Models.AppSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("WebApplication1.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Iterations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Pesel")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApplication1.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BookedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CanceledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookingId");

                    b.HasIndex("PatientId");

                    b.HasIndex("SlotId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("WebApplication1.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DoctorId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            Email = "jan@clinic.com",
                            Name = "Jan",
                            Phone = "500111222",
                            Surname = "Kowalski"
                        },
                        new
                        {
                            DoctorId = 2,
                            Email = "anna@clinic.com",
                            Name = "Anna",
                            Phone = "500333444",
                            Surname = "Nowak"
                        },
                        new
                        {
                            DoctorId = 3,
                            Email = "marek@clinic.com",
                            Name = "Marek",
                            Phone = "500555666",
                            Surname = "Lis"
                        },
                        new
                        {
                            DoctorId = 4,
                            Email = "ewa@clinic.com",
                            Name = "Ewa",
                            Phone = "500777888",
                            Surname = "Zawisza"
                        },
                        new
                        {
                            DoctorId = 5,
                            Email = "piotr@clinic.com",
                            Name = "Piotr",
                            Phone = "501222333",
                            Surname = "Zieliński"
                        },
                        new
                        {
                            DoctorId = 6,
                            Email = "katarzyna@clinic.com",
                            Name = "Katarzyna",
                            Phone = "502333444",
                            Surname = "Mazur"
                        },
                        new
                        {
                            DoctorId = 7,
                            Email = "tomasz@clinic.com",
                            Name = "Tomasz",
                            Phone = "503444555",
                            Surname = "Wójcik"
                        },
                        new
                        {
                            DoctorId = 8,
                            Email = "joanna@clinic.com",
                            Name = "Joanna",
                            Phone = "504555666",
                            Surname = "Piotrowska"
                        },
                        new
                        {
                            DoctorId = 9,
                            Email = "adam@clinic.com",
                            Name = "Adam",
                            Phone = "505666777",
                            Surname = "Konieczny"
                        },
                        new
                        {
                            DoctorId = 10,
                            Email = "magda@clinic.com",
                            Name = "Magdalena",
                            Phone = "506777888",
                            Surname = "Lewandowska"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.DoctorSpecialization", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DoctorId", "SpecializationId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("DoctorSpecializations");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            SpecializationId = 1
                        },
                        new
                        {
                            DoctorId = 1,
                            SpecializationId = 6
                        },
                        new
                        {
                            DoctorId = 2,
                            SpecializationId = 2
                        },
                        new
                        {
                            DoctorId = 1,
                            SpecializationId = 7
                        },
                        new
                        {
                            DoctorId = 2,
                            SpecializationId = 6
                        },
                        new
                        {
                            DoctorId = 3,
                            SpecializationId = 1
                        },
                        new
                        {
                            DoctorId = 4,
                            SpecializationId = 3
                        },
                        new
                        {
                            DoctorId = 5,
                            SpecializationId = 4
                        },
                        new
                        {
                            DoctorId = 6,
                            SpecializationId = 2
                        },
                        new
                        {
                            DoctorId = 7,
                            SpecializationId = 5
                        },
                        new
                        {
                            DoctorId = 8,
                            SpecializationId = 3
                        },
                        new
                        {
                            DoctorId = 9,
                            SpecializationId = 4
                        },
                        new
                        {
                            DoctorId = 10,
                            SpecializationId = 1
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            Address = "Warszawa",
                            Email = "ola@ex.com",
                            Name = "Ola",
                            Phone = "501000999",
                            Surname = "Olszewska"
                        },
                        new
                        {
                            PatientId = 2,
                            Address = "Kraków",
                            Email = "piotr@ex.com",
                            Name = "Piotr",
                            Phone = "501000888",
                            Surname = "Zieliński"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Slot", b =>
                {
                    b.Property<int>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("TEXT");

                    b.HasKey("SlotId");

                    b.HasIndex("DoctorId", "StartAt")
                        .IsUnique();

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("WebApplication1.Models.Specialization", b =>
                {
                    b.Property<int>("SpecializationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecializationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SpecializationId");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            SpecializationId = 1,
                            SpecializationName = "Kardiolog"
                        },
                        new
                        {
                            SpecializationId = 2,
                            SpecializationName = "Dermatolog"
                        },
                        new
                        {
                            SpecializationId = 6,
                            SpecializationName = "Urolog"
                        },
                        new
                        {
                            SpecializationId = 7,
                            SpecializationName = "Fizjoterapeuta"
                        },
                        new
                        {
                            SpecializationId = 3,
                            SpecializationName = "Laryngolog"
                        },
                        new
                        {
                            SpecializationId = 4,
                            SpecializationName = "Okulista"
                        },
                        new
                        {
                            SpecializationId = 5,
                            SpecializationName = "Neurolog"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.AppSession", b =>
                {
                    b.HasOne("WebApplication1.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication1.Models.Booking", b =>
                {
                    b.HasOne("WebApplication1.Models.Patient", "Patient")
                        .WithMany("Bookings")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Slot", "Slot")
                        .WithOne("Booking")
                        .HasForeignKey("WebApplication1.Models.Booking", "SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Slot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication1.Models.DoctorSpecialization", b =>
                {
                    b.HasOne("WebApplication1.Models.Doctor", "Doctor")
                        .WithMany("DoctorSpecializations")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Specialization", "Specialization")
                        .WithMany("DoctorSpecializations")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("WebApplication1.Models.Slot", b =>
                {
                    b.HasOne("WebApplication1.Models.Doctor", "Doctor")
                        .WithMany("Slots")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("WebApplication1.Models.Doctor", b =>
                {
                    b.Navigation("DoctorSpecializations");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("WebApplication1.Models.Patient", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("WebApplication1.Models.Slot", b =>
                {
                    b.Navigation("Booking");
                });

            modelBuilder.Entity("WebApplication1.Models.Specialization", b =>
                {
                    b.Navigation("DoctorSpecializations");
                });
#pragma warning restore 612, 618
        }
    }
}
